baseURL: 'https://marvinsextro.de/'
languageCode: en-us
title: Marvin Sextro
theme: PaperMod
menu:
  main:
  - identifier: projects
    name: Projects
    url: '/projects'
    weight: 10
  - identifier: posts
    name: Posts
    url: '/posts'
    weight: 20
params:
  description: My personal website.
  profileMode:
    enabled: true
    title: Marvin Sextro
    subtitle: Data Scientist at Aignostics
    imageUrl: '/profile.jpg'
    imageWidth: 120
    imageHeight: 120
  socialIcons:
    - name: email
      url: 'mailto:marvin.sextro@gmail.com'
    - name: github
      url: 'https://github.com/marvinsxtr'
    - name: linkedin
      url: 'https://linkedin.com/in/marvinsxtr'
    - name: twitter
      url: 'https://twitter.com/marvinsxtr'
  editPost:
    URL: 'https://github.com/marvinsxtr/personal-website/tree/main/content'
    Text: "Suggest Changes"
    appendFilePath: true