baseURL: 'https://marvinsextro.de/'
languageCode: en-us
title: Marvin
theme: PaperMod
params:
  author: Marvin Sextro
  description: My personal website.
  profileMode:
    enabled: true
    title: Marvin Sextro
    subtitle: Computer Science Student @ TU Berlin
    imageUrl: 'https://gravatar.com/avatar/099cbcdf60f0bee9c5600f293df2b0ea?s=200'
    imageWidth: 120
    imageHeight: 120
  socialIcons:
    - name: email
      url: 'mailto:marvin.sextro@gmail.com'
    - name: github
      url: 'https://github.com/marvinsxtr'
    - name: linkedin
      url: https://linkedin.com/in/marvinsxtr
    - name: twitter
      url: https://twitter.com/marvinsxtr