baseURL: 'https://marvinsextro.de/'
languageCode: en-us
title: Marvin Sextro
theme: PaperMod
menu:
  main:
  - identifier: research
    name: Research
    url: '/research'
    weight: 10
  - identifier: posts
    name: Posts
    url: '/posts'
    weight: 20
params:
  description: My personal website.
  profileMode:
    enabled: true
    title: Marvin Sextro
    subtitle: Machine Learning for Precision Medicine
    imageUrl: '/profile.jpg'
    imageWidth: 120
    imageHeight: 120
    buttons:
      - name: Research Profile
        url: "/research"
  socialIcons:
    - name: email
      url: 'mailto:marvin.sextro@gmail.com'
    - name: github
      url: 'https://github.com/marvinsxtr'
    - name: googlescholar
      url: 'https://scholar.google.com/citations?user=S2JS0ZIAAAAJ'
    - name: linkedin
      url: 'https://linkedin.com/in/marvinsxtr'
    - name: x
      url: 'https://x.com/marvinsxtr'